config/routes.rb
Rails.application.routes.draw do
  
  post "sessions" => "sessions#create", as: :create_session
  delete "sessions" => "sessions#destroy", as: :destroy_session

  resources :devices, except: [:edit, :new] do
  	member do
  		post "lock" => "devices#lock"
  		post "unlock" => "devices#unlock"
  		get "tracking_route" => "devices#tracking_route"
  	end
  	collection do
  		post "track" => "devices#track"
  	end
  end
  root 'home#index'
end

app/models/concerns/twilio_api.rb
module TwilioApi
	extend ActiveSupport::Concern
	attr_accessor :twilio_client
	
	included do
    @twilio_client = Twilio::REST::Client.new ENV['TWILIO_ASID'], ENV['TWILIO_ATOK']
  end

  def send_sms(number, message)
		@obj = @twilio_client.account.sms.messages.create(
		  :from => ENV['TWILIO_NUMBER'],
		  :to => number,
		  :body => message
		)
	end
end

app/models/device.rb
class Device < ActiveRecord::Base
	belongs_to :user
	has_many :tracking_routes
	include TwilioApi

	def is_locked?
		self.lock
	end

	def is_unlock?
		!self.is_locked?
	end

	def last_tracking_route
		@last_tracking_route ||= self.tracking_routes.includes(:positions).order("started_at desc").first
	end

	def send_position_request
		position_request_message = "the message..." #TODO: Change this message to the actual sms request message
		self.send_sms(self.phone_number, position_request_message)
	end

	def start_tracking
		if self.is_unlock?
			self.lock = true
			self.tracking_routes << TrackingRoute.new(started_at: DateTime.now )
			self.save
			puts "Sending Position Request..."
			#self.send_position_request
			return true
		else
			puts "Sending Position Request..."
			return false
		end
	end

	def stop_tracking
		if self.is_locked?
    	tracking_route = self.last_tracking_route
    	tracking_route.end_at = DateTime.now
    	tracking_route.save
    	self.lock = false
    	self.save
		else
			return false
		end
	end

	def track_position(message)
		route = self.last_tracking_route
		route.positions << Position.build_from_message(message) unless route.nil?
	end

	def register_device(user)
		if self.user_id.nil?
			self.user_id = user.id
			self.save
		else
			return false
		end
	end
end

app/models/foursquare.rb
class Foursquare
	def self.query(params)
		uri = URI.parse("https://api.foursquare.com/v2/venues/search")  
		http_query = URI.encode_www_form(params)
		uri.query = http_query
		puts uri.to_s
		http = Net::HTTP.new(uri.host,uri.port)
		http.use_ssl = true
		http.ca_file = Rails.root.join("lib/ca.crt").to_s
		http.verify_mode = OpenSSL::SSL::VERIFY_NONE
		req = Net::HTTP::Get.new(uri.path)
		res = http.request(req)
		JSON.parse(res.body)
	end
end

app/models/position.rb
class Position < ActiveRecord::Base
	belongs_to :tracking_route

	def self.build_from_message(message)
		#TODO GET THE GOOGLE MAPS URL SENT BY THE DEVICE AND PARSE IT TO LATTITUDE AND LONGITUDE FORMAT
		self.new(message: message)
	end
end

app/models/tracking_route.rb
class TrackingRoute < ActiveRecord::Base
  belongs_to :device
  has_many :positions

  def has_stopped?
  	self.end_at.present?
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :devices

  def self.sign_up_or_sign_in(user_params)
  	user = self.where(user_params).first
  	unless user.present?
  		user = User.create(user_params)
  	end
  	return user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead....
  protect_from_forgery with: :null_session


	def current_user
		@current_user ||=  User.first 
	end
	helper_method :current_user

	def user_signed_in?
		puts current_user
		if current_user.nil?
			render json: {message: "User not authenticated"}, :status=>401
		end
	end

	def restrict_acces_to_app
		unless request.headers["app-token"] == ENV["APP_TOKEN_ID"]
			render json: {message: "APP_TOKEN missing"}, :status=>403
		end
	end

end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  #before_action :restrict_acces_to_app, except: [:track]
  before_action :user_signed_in?, except: [:track]
  before_action :set_device, except: [:index, :create]

  # GET /devices
  # GET /devices.json
  def index
    @devices = current_user.devices.order(:alias_name)
  end

  # GET /devices/1
  # GET /devices/1.json
  def show
  end

  # POST /devices
  # POST /devices.json
  def create
    puts params
    @device = Device.where(phone_number: params[:phone_number]).first    
    respond_to do |format|
      if @device.nil?
        format.json { render json: {message: "Sorry, the submited device is not registered"}, status: :ok }
      elsif @device.register_device(current_user)
        @device.alias_name = params[:alias_name]
        @device.save
        format.json { render json: {message: "The submited device was registered succesfully"}, status: :ok }
      else
        format.json { render json: {message: "Sorry, the Device has already been registered"}, status: :ok }
      end
    end
  end

  # PATCH/PUT /devices/1
  # PATCH/PUT /devices/1.json
  def update
    respond_to do |format|
      if @device.update(device_params)
        format.json { render :show, status: :ok, location: @device }
      else
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /devices/1
  # DELETE /devices/1.json
  def destroy
    @device.user_id = nil
    @device.save
    respond_to do |format|
      format.json { head :no_content }
    end
  end

  def lock
    respond_to do |format|
      if @device.start_tracking
        puts "Start Tracking"
        format.json { render json: {message: "The Device has been locked"},status: :ok }
      else
        format.json { render json: {message: "The Device has already been locked"},status: :ok }
      end
    end
  end

  def unlock
    respond_to do |format|
      if @device.stop_tracking
        puts "Stop Tracking"
        format.json { render json: {message: "The Device has been unlocked"},status: :ok }
      else
        format.json { render json: {message: "The Device has already been unlocked"},status: :ok }
      end
    end
  end

  def tracking_route
    @device = Device.where(id: params[:id]).first
    @tracking_route = @device.last_tracking_route || {}
  end

  def track
    if params[:To] == ENV["TWILIO_NUMBER"]
      @device = Device.where(phone_number: params[:From]).first
      if @device.is_locked?
        @device.track_position(params[:Body])
      end
      @unauthorized = false
    else
      @unauthorized = true
      render json: {message: "Request not authenticated"}, :status=>403
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_device
      @device = current_user.devices.where(id:params[:id]).first
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def device_params
      params[:device]
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  #before_action :restrict_acces_to_app
  before_action :user_signed_in?, except: [:create]
  def create
  	@current_user = User.sign_up_or_sign_in(user_params)
  end

  def destroy
  	@current_user.facebook_token = nil
  	@current_user.save
  	respond_to do |format|
  		format.json { render json: {message: "Session Has ended"}, status: :ok }
  	end
  end

  def user_params
  	params.require(:user).permit!
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/positions_helper.rb
module PositionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/twilio_handler_helper.rb
module TwilioHandlerHelper
end

app/views/devices/_form.html.erb
<%= form_for(@device) do |f| %>
  <% if @device.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@device.errors.count, "error") %> prohibited this device from being saved:</h2>

      <ul>
      <% @device.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/devices/edit.html.erb
<h1>Editing device</h1>

<%= render 'form' %>

<%= link_to 'Show', @device %> |
<%= link_to 'Back', devices_path %>

app/views/devices/index.html.erb
<h1>Listing devices</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @devices.each do |device| %>
      <tr>
        <td><%= link_to 'Show', device %></td>
        <td><%= link_to 'Edit', edit_device_path(device) %></td>
        <td><%= link_to 'Destroy', device, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Device', new_device_path %>

app/views/devices/new.html.erb
<h1>New device</h1>

<%= render 'form' %>

<%= link_to 'Back', devices_path %>

app/views/devices/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_device_path(@device) %> |
<%= link_to 'Back', devices_path %>

app/views/devices/track.xml.erb
<?xml version="1.0" encoding="UTF-8"?>
<% unless @unauthorized %>
	<Response>
		<% if @device.is_locked? %>
			<Message>THE MESSAGE TO REQUEST NEW POSITION</Message>
		<% end %>
	</Response>
<% end %>

app/views/home/index.html.erb
<h1>Welcome to ooDoo</h1>
<h2>Landing Page</h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Oodoo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>